project:
  type: website

website:
  title: "Wiki"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - auto: onboarding/
      - auto: team/
      - auto: runbooks/
      - auto: platforms-and-tools/
      - auto: team/
      - auto: training/
      - auto: misc/
    collapse-level: 1

format:
  html:
    theme: cosmo
    toc: true



