project:
  type: website

website:
  title: "Wiki"
  page-footer:
    left: "Internal documentation of the Research Computing Team"
    right: 
      - icon: github
        href: https://github.com/murphyqm/testing-wiki
  repo-url: https://github.com/murphyqm/testing-wiki
  repo-actions: [edit, source, issue]
  sidebar:
    style: "docked"
    search: true
    contents: 
      - auto: onboarding/
      - auto: team/
      - auto: runbooks/
      - auto: platforms-and-tools/
      - auto: team/
      - auto: training/
      - auto: misc/
    collapse-level: 1

format:
  html:
    theme: cosmo
    toc: true



