on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Quarto test and publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        if: github.event_name != 'pull_request'  # Only publish on push to main, not on PRs
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render only (for pull requests)
        if: github.event_name == 'pull_request'
        run: quarto render
